language: node_js
node_js:
- '8'
before_script:
- npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: _book
  on:
    branch: master
env:
  global:
    secure: FLykhvwBkYDTjKPKGyl16eUVDiJhyLc7/51PvjtFjTB/qQO8MygfNCEK0aMmP32icD1wvdg1LdhWNVj8SZE/6jVE1YTm9vV9g0HfX6q7Zr+LqI6TObVjKjtRr9HASULQf3TDseB2yC8SCjKgOv6UcvUYrFOZzOwMVIKZjSHpI2UYR4FG3m35UDAjATNN57l/glPpV4CFHgFLgcINiCmPp/eDcZpbJaFuYZ6zfch0y013cUA4vBeViy2zGVr/YZnH1Z/3gnGe4ihX9wb/QNuhjkn7Okaompgq0VVCJnZeS0JhVCE3zsCUh0s95nEI6sO5AZQX7R9Qf1dgfI7qYqYqW9Ghjvy0E+7xc02Rk9gBrSqPfiWkafltvJBQelFSFSuIDaWhUEM/ICFJU1k7dJaeW/Kg7MQQBqGu/sl+1+rJNNc5ChkT8zDGr6HB3zKYZbfUZdloi5kxRijt6NFEnxHNpJC0YuXJBELzkSwjnBLVg1J31G4QW29QCkWUi+BdFWm8+tTDzjEmyzd2e59yBTcWUAeFf+f+UA5Lq2W43N5JbpHHeqheo4RAMHFv+V7kfHDf8M2LXabk3/RJVn/6x8Fw0GtB8fh/tZie7WYH0uo2qyj76/jl+FjhgVGfbRg6cravxkAlk70yDz0wbqJhXcnPYw/tRvMUFaoR2XVI/n5GSIM=
